### ISSUE TITLE
你好，下载了你上传的风叶结冰数据集，解压缩需要密码，请问密码是什么？

### ISSUE THREAD

**Issue by YangYing77** [XinArkh/Industrial_BigData_Competition#1]

**Comment by XinArkh** [comment]
你好，在README.txt中已作说明，所有解压密码均为2017

**Comment by YangYing77** [comment]
非常感谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wu Xin"<notifications@github.com&gt;; 
发送时间: 2020年6月3日(星期三) 下午3:52
收件人: "XinArkh/Industrial_BigData_Competition_2017"<Industrial_BigData_Competition_2017@noreply.github.com&gt;; 
抄送: "1410641590"<1410641590@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [XinArkh/Industrial_BigData_Competition_2017] 你好，下载了你上传的风叶结冰数据集，解压缩需要密码，请问密码是什么？ (#1)





 
你好，在README.txt中已作说明，所有解压密码均为2017
